Add ability to redact name and address from donor records
datamade/openness-project-nmid pull request #179
Opened 2023-12-13 22:11 UTC by hancush

## Overview

See title. Redacting information from one contribution record will also redact other contributions from the same donor.

Only authenticated users can redact records.

Redacted records should appear as redacted on candidate and committee detail pages, as well as in contribution exports. They should also be excluded from site search results.

### Demo

<img width="1624" alt="Screenshot 2023-12-13 at 4 06 50 PM" src="https://github.com/datamade/openness-project-nmid/assets/12176173/6bd927a6-cebf-4707-b88b-043507573b89">
<img width="1624" alt="Screenshot 2023-12-13 at 4 06 43 PM" src="https://github.com/datamade/openness-project-nmid/assets/12176173/c2212047-6bc3-4b72-9e39-d01ef3e142ee">
<img width="1624" alt="Screenshot 2023-12-13 at 3 51 12 PM" src="https://github.com/datamade/openness-project-nmid/assets/12176173/13ec0395-fc8f-4740-b147-45e3cc6ad3f0">

## Testing Instructions

* View a contribution and confirm you don't see the redaction form.
* Create a super user on the deploy preview and log in.
* Navigate to a contribution and confirm you can see the redaction form.
* Redact the record.
* Navigate to the detail page of the recipient, and confirm the donor's details are redacted.
* Unredact the record.
* Navigate to the detail page of the recipient, and confirm the donor's detail are not redacted.

2023-12-13 22:11 UTC, hancush commented on camp_fin/api_parts.py
> +    def to_representation(self, instance):
Material change.

2023-12-13 22:11 UTC, hancush commented on camp_fin/api_parts.py
> +    def get_company_name(self, instance):
Material changes.

2023-12-13 22:12 UTC, hancush commented on camp_fin/management/commands/import_api_data.py
> +        if record["Contributor Code"] not in ("Individual", "Candidate"):
Store company names as company names.

2023-12-13 22:12 UTC, hancush commented on camp_fin/management/commands/import_api_data.py
> +            self._cache["contact"][tuple(contact_kwargs.values())] = contact
Adds caching for contacts.

2023-12-19 16:19 UTC, derekeder requested changes
Setting the checkbox and submitting does redact as expected, however, after reloading the page, the checkbox is unchecked even though it is redacted. Clicking Submit with the unchecked box does not seem to save / unredact the record. 

Would this be easier to remove the checkbox and have the button say 'Redact' or 'Unredact' based on the record state?

Unrelated to these changes:

Seeing a build error on the deploy preview. Changing the web dyno in `app.json` to `standard-1x` will resolve this.

Getting a 500 error on the top 25 donations for committee pages (other lists are fine): https://openness-pro-hcg-redact-nuvhlb.herokuapp.com/api/top-donors/513/?entity_type=pac

2023-12-19 16:19 UTC, derekeder commented on camp_fin/templates/camp_fin/contribution-detail.html
> +                        <input type="submit" value="Submit" class="btn btn-primary" />
Could we have this button say Redact or Unredact depending on state instead of using a checkbox?

2023-12-19 18:34 UTC, hancush commented on camp_fin/templates/base-detail.html
> +                                <a href='/search/?term=<%= encodeURIComponent(transaction.company_name.replace("\'", "")) %>'>
5 years, nbd

2023-12-19 20:02 UTC, hancush commented
Changes in. Can you have another pass?

2023-12-19 20:56 UTC, derekeder requested changes
button works to redact, but it doesn't change to 'Unredact' after I save. Here's 2 examples I did it on: 

https://openness-pro-hcg-redact-ehwzmc.herokuapp.com/contributions/1676253/
https://openness-pro-hcg-redact-ehwzmc.herokuapp.com/contributions/1621989/

For the top 25 donors, seeing a few things:

- this one has nothing in top 25, but lots in 'All donations': https://openness-pro-hcg-redact-ehwzmc.herokuapp.com/committees/nmhrcc-new-mexico-house-republican-campaign-committee-648/
- this one only shows 1 in the top 25: https://openness-pro-hcg-redact-ehwzmc.herokuapp.com/committees/new-mexico-strong-607/

2023-12-19 21:12 UTC, hancush commented
@derekeder Can you hard refresh after you redact/unredact? It's working fine on Chrome – what browser are you in?

![redact](https://github.com/datamade/openness-project-nmid/assets/12176173/1e1c6716-13d9-4ca0-908d-1ab4bc3930b2)

2023-12-19 21:13 UTC, hancush commented
Also, Top 25 donors looks buggy indeed. Would you mind if I looked at that separately?

2023-12-19 21:19 UTC, derekeder commented
huh weird. im in firefox and just tried in chrome and it works. here's me editing the same record in both browsers:


https://github.com/datamade/openness-project-nmid/assets/919583/dbe8dede-bf3a-4a60-b4d6-c6adb4ad8b08

2023-12-19 21:35 UTC, hancush commented
Can you disable your ad blockers and try again? It's working on fresh Firefox install for me:

![redact-ff](https://github.com/datamade/openness-project-nmid/assets/12176173/6d2cee1e-f711-4218-bbb6-ebdb265e0e89)

2023-12-19 21:40 UTC, hancush commented
Also, @derekeder, just pushed a change fixing top donors! Nvm about addressing separately.

2023-12-20 16:21 UTC, derekeder commented
got an error when trying to redact this donation: https://openness-pro-hcg-redact-ehwzmc.herokuapp.com/contributions/1428368/

https://github.com/datamade/openness-project-nmid/assets/919583/4933a98b-22cc-4c43-966a-92946ffafd19


redaction name still showing up on the Top 25 page after redacting, though it shows up as redacted on 'All donations':

<img width="1191" alt="Screenshot 2023-12-20 at 10 18 37 AM" src="https://github.com/datamade/openness-project-nmid/assets/919583/e6ddd478-cf4e-47e3-8241-823300edbebd">

<img width="1174" alt="Screenshot 2023-12-20 at 10 19 02 AM" src="https://github.com/datamade/openness-project-nmid/assets/919583/2fb7ba4f-5266-4940-9cf8-9db99bd24ad5">

2023-12-20 16:38 UTC, hancush commented
@derekeder Damn, this data is so messy! Just pushed up a patch, try again when it's done deploying.

2023-12-20 20:20 UTC, derekeder approved these changes
k working as expected now.

still having issues with firefox, even after turning off all extensions. chrome works fine though

2023-12-21 14:46 UTC, merged